### ISSUE TITLE
My Max Health is weird in the latest update

### ISSUE THREAD

**Issue by GeradesoLukas** [P03W/RPGStats#41] opened 2021-03-31 19:00 UTC
Hey, so I am using the latest Version, and I am level 20 in one of my Survival worlds. Now I have 2 rows of extra hearts. The Level up adds 10 hearts instead of 1 health point I guess

**Comment by P03W** [comment] 2021-03-31 19:01
level 20 in what?

**Comment by GeradesoLukas** [comment] 2021-03-31 23:08
Hey sorry, I didn't specify. It is level 20 in Defense, and I am restarting the game, so it can happen

**Comment by P03W** [comment] 2021-03-31 23:13
Ah yeah that would do it

Ill get a patch out

**Comment by P03W** [comment] 2021-03-31 23:24
Actually I cant reproduce this, could you possibly send a video?

**Comment by GeradesoLukas** [comment] 2021-04-04 14:04
Okay, so I found the actual issue. It is still the same steps, but you need to level up to that number and use 10 heart canisters from the Trinket Heart Canisters mod. Then You will get 20 Hearts after restarting the game instead of only 10. You also get the health from the defense stat on top.

Heart Canisters: https://www.curseforge.com/minecraft/mc-mods/trinket-heart-canisters

**Comment by P03W** [comment] 2021-04-04 14:05
Arg, I was worried about this

I'll do what I can

**Comment by GamyGamer** [comment] 2021-04-08 10:39
I think it might be related to this code that was added in response to #37. I am using tiered ( https://www.curseforge.com/minecraft/mc-mods/tiered ) that can give more HP based on tier. Problem arise when player leaves world and join back.

Steps
1. get armor that modify HP
2. wear it
3. log out
4. log in
5. Congratulation, you have now way more HP than normal

**Comment by P03W** [comment] 2021-04-09 00:35
Can any of you confirm if this is fixed in 4.0.0?

**Comment by P03W** [comment] 2021-04-11 20:49
Closing in favor of #48

**Closed by P03W** 2021-04-11 20:49 UTC
Labels: bug, mod compatibility
