### ISSUE TITLE
Translations do not work while Inspecio is installed

### ISSUE THREAD

**Issue by BlackDragon126** [P03W/RPGStats#100] opened 2022-04-03 10:12 UTC
as mod work's fine so far i can see 
the commad /rpgstats does not show info of exp gain / need 
it show sting error

**Comment by P03W** [comment] 2022-04-03 13:48
Issues templates exist for a reason, use them

Also please provide any information whatsoever

**Comment by P03W** [comment] 2022-04-03 13:52
Cannot reproduce in dev environment, please provide context or ill just close this issue

**Comment by BlackDragon126** [comment] 2022-04-03 14:04
after typing /rpgstats  shows this 

![image](https://user-images.githubusercontent.com/84410523/161431726-155d0831-ca02-4bab-aba4-208c6c0d5f96.png)
no erros shows in debug output

**Comment by P03W** [comment] 2022-04-03 14:06
Whats your language set to? because that looks like translations arent loading

**Comment by BlackDragon126** [comment] 2022-04-03 14:06
englise (US)

**Comment by P03W** [comment] 2022-04-03 14:08
Is this singleplayer or multiplayer? do you have other mods installed?

**Comment by BlackDragon126** [comment] 2022-04-03 14:09
right now is single 
i tried now in multiplayer 
same problem

**Comment by BlackDragon126** [comment] 2022-04-03 14:14
mods yes alot

**Comment by BlackDragon126** [comment] 2022-04-03 14:16
need to restart pc could'nt take picture 
i got alot of mods loaded 
![image](https://user-images.githubusercontent.com/84410523/161432291-dfb409ed-a8ab-4db5-a546-4d4ee4eb3911.png)
![image](https://user-images.githubusercontent.com/84410523/161432302-4a9f9a59-9115-4c8a-83e2-252c1ca5e686.png)

**Comment by BlackDragon126** [comment] 2022-04-03 14:21
with only rpgstats loaded shows fine 
i don't know witch  mods is make it to show like this

**Comment by Neonis00** [comment] 2022-04-03 14:38
Just wanted to add that I also had the same issue pop up for myself, and it ended up being an incompatibility with the mod, "Bee Better (1.9.0-1.18.2)".

**Comment by BlackDragon126** [comment] 2022-04-03 14:47
ok i'll keep that in mind 
right now i have 27 mods left to check witch one making this

**Comment by BlackDragon126** [comment] 2022-04-03 14:50
found it is this little shit 
![image](https://user-images.githubusercontent.com/84410523/161433763-7e1f1eb4-f61d-4750-83df-7323bc5622d9.png)

**Comment by P03W** [comment] 2022-04-03 16:33
Opened issue on inspecio repo, seems to be an incompatibility between them and the mod I use for some translations

**Comment by P03W** [comment] 2022-05-25 02:37
Should be fixed in 4.3.11

**Closed by P03W** 2022-05-25 02:37 UTC
Labels: bug, mod compatibility
