### ISSUE TITLE
Mining Stat doesn't work

### ISSUE THREAD

**Issue by bubbaryebread** [P03W/RPGStats#40] opened 2021-03-15 23:43 UTC
I've noticed recently that the mining stat isn't working. I'm building an underground base, and noticed that I wasn't leveling up despite how much I was mining. I know that the farming stat still works fine, but I haven't tested any of the others to see if they work.

**Comment by P03W** [comment] 2021-03-15 23:48
Are you mining ores? Those are the only blocks that give XP

If you are and still not getting XP, could you provide your log?

**Comment by P03W** [comment] 2021-03-17 02:42
I cant reproduce not gaining xp in dev, if you havent provided logs ill eventually have to close this

**Comment by bubbaryebread** [comment] 2021-03-17 20:57
Sorry for the late response! I forgot that it only applied to ores, so I was just confused. It works just fine, I'm just oblivious lol

**Comment by P03W** [comment] 2021-03-17 21:00
Thats alright, glad this is resolved

**Closed by P03W** 2021-03-17 21:00 UTC
Labels: awaiting feedback, bug
